### ISSUE TITLE
Please avoid putting large files on Github

### ISSUE THREAD

**Issue by vladimirkovacevic** [amrsic14/fm_index_and_burrows_wheeler#3]
Github is for source code. Test data up to a few megs is acceptable if really really necessary.
"Multiple revisions of large files increase the clone and fetch times for other users of a repository. To remove a large file from your repository, you must completely remove it from your local repository and from GitHub."

**Comment by vladimirkovacevic** [comment]
Instead of adding large files you can add instructions how to download them,

**Comment by amrsic14** [comment]
Thank you for the suggestion. The issue is solved.
